version: 2
updates:
- package-ecosystem: npm
  directory: "/nodecli"
  schedule:
    interval: daily
    time: "05:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: "08:00"
    timezone: Japan
  open-pull-requests-limit: 10
  assignees:
    - kakikubo
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  labels:
    - "GH Actions"
    - "dependencies"
