name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: js-primer-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nodecli

    steps:
      - uses: actions/checkout@v5
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install Dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Install Dependencies todoapp
        run: npm install
        working-directory: ./todoapp
      - name: Run test todoapp
        run: npm test
        working-directory: ./todoapp
